# trigger build
name: editprox
description: A video editing app like CapCut + Motion Ninja
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  ffmpeg_kit_flutter: ^4.5.1
  file_picker: ^5.2.5
  path_provider: ^2.0.14
  path: ^1.8.3

flutter:
  uses-material-design: true
